version: '2'

services:
  jupyter:
    container_name: ml_dm_hse_minor
    image: festline/ml_dm_hse_minor
    working_dir: /notebooks
    ports:
      - "8888:8888"
    volumes:
      - .:/notebooks

